app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check

logout:
    path: /logout

user_nick_test:
    path: /nick-test
    defaults: { _controller: AppBundle:User:nickTest }
    methods: [POST]

